version: "3.1"
services:
    php-fpm:
      build: docker/php-fpm
      container_name: php-fpm-articles
      working_dir: /app
      volumes:
      - ./app:/app
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    webserver:
      image: nginx:alpine
      container_name: nginx-articles
      links:
          - php-fpm
      working_dir: /app
      volumes:
          - ./app:/app
          - ./config/nginx.conf:/etc/nginx/nginx.conf
      ports:
       - "8080:80"

    mysql:
      image: mysql:5.7
      container_name: mysql-articles
      working_dir: /app
      volumes:
      - ./app:/app
      - ./app:/app
      environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=articles
      - MYSQL_USER=belka
      - MYSQL_PASSWORD=belka
      ports:
      - "8082:3306"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin-articles
      restart: always
      links:
      - mysql:mysql
      ports:
      - "8083:80"
      environment:
        PMA_HOST: mysql
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: secret
