route1:
    path:     /create-data-base
    defaults: { _controller: 'GenerationDump::index' }
routeGetArticles:
    path:     /
    defaults: { _controller: 'ArticleController::getArticles' }
routeGetArticle:
    path:     /articles/{id}
    defaults: { _controller: 'ArticleController::getArticle' }
    requirements:
      id: '[0-9]+'

routeAdminGetArticles:
    path:     /admin/articles
    defaults: { _controller: 'AdminArticleController::getArticles' }
routeAdminUpdateArticles:
    path:     /admin/articles/edit/{id<\d+>?}
    defaults: { _controller: 'ArticleController::updateArticle' }
routeAdminCreateArticles:
    path:     /admin/articles/create
    defaults: { _controller: 'AdminArticleController::createArticle' }
routeAdminDeleteArticles:
    path:     /admin/articles/delete/{id<\d+>?}
    defaults: { _controller: 'AdminArticleController::deleteArticle' }